server:
  port: 8021
spring:
  #给项目来个名字
  application:
    name: rabbitmq-producer
  #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: user
    password: root
    #虚拟host 可以不设置,使用server默认host
    virtual-host: /virtual

    #确认消息已发送到交换机(Exchange)
    publisher-confirms: true
    #确认消息已发送到队列(Queue)
    publisher-returns: true